developer_task:
  description: >
    Write Kubernetes/OpenShift yaml code for the given requirement: {instruction} 
    Make sure that the provided code aligns with the security best practices and is highly performant. 
    Also provide all the steps required to deploy this code.
  expected_output: >
    Generated Kubernetes/OpenShift yaml files alongwith the detailed instructions/steps of deployment
  agent: developer

